### ISSUE TITLE
resume button redirecting to another broken html site

### ISSUE THREAD

**Issue by naaam-h-siddhu** [shubhansu-kr/shubhansu-kr.github.io#1]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/85333344/207325843-a7e0cd7f-85be-4474-add6-57439ca173d9.png">

**Comment by shubhansu-kr** [comment]
Hey @naaam-h-siddhu, 
Thanks for pointing out the broken link, i will be fixing the link asap.
